
name: MLOps Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PYTHON_VERSION: '3.12'
  SPACE_NAME: Shramik121/tourism-rf-model
jobs:
  ml-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 pandas==2.2.2 scikit-learn==1.6.1 joblib==1.4.2 dill==0.3.8 huggingface_hub==0.23.0 flask==3.0.3 waitress==3.0.0 pytest==8.3.3 datasets==2.20.0
      - name: Create directories
        run: mkdir -p data models
      - name: Data Preparation
        run: python src/data_prep.py
      - name: Model Training
        run: python src/train.py
      - name: Model Evaluation
        run: python src/evaluate.py
      - name: Run Tests
        run: pytest tests/ --verbose
      - name: Deploy to Hugging Face
        run: python src/deploy.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
